# Generated by Django 5.2.8 on 2025-11-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogamdo',
            name='game_step',
            field=models.IntegerField(default=0),
        ),
    ]
